from BColors import BColors

def migrate_permission_copies(cursor, postgres_cursor, **kwargs):
    print(f"{BColors.WARNING}Migrating permission_copies...{BColors.ENDC}")
    insert_query = '''
    INSERT INTO public."PermissionCopy" ("tableName", mode, "createdAt", "updatedAt") VALUES (%s, %s, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    '''
    
    permission_copies = [
        ("Modules", "Create"),
        ("Modules", "Read"),
        ("Modules", "Update"),
        ("Modules", "Delete"),
        ("Lessons", "Create"),
        ("Lessons", "Read"),
        ("Lessons", "Update"),
        ("Lessons", "Delete"),
        ("Badges", "Create"),
        ("Badges", "Read"),
        ("Badges", "Update"),
        ("Badges", "Delete"),
        ("Skills", "Create"),
        ("Skills", "Read"),
        ("Skills", "Update"),
        ("Skills", "Delete"),
        ("Sub Skills", "Create"),
        ("Sub Skills", "Read"),
        ("Sub Skills", "Update"),
        ("Sub Skills", "Delete"),
        ("Skill Sections", "Create"),
        ("Skill Sections", "Read"),
        ("Skill Sections", "Update"),
        ("Skill Sections", "Delete"),
        ("Icons", "Create"),
        ("Icons", "Read"),
        ("Icons", "Update"),
        ("Icons", "Delete"),
        ("Quizzes", "Create"),
        ("Quizzes", "Read"),
        ("Quizzes", "Update"),
        ("Quizzes", "Delete"),
        ("Admins", "Create"),
        ("Admins", "Read"),
        ("Admins", "Update"),
        ("Admins", "Delete"),
        ("Users", "Create"),
        ("Users", "Read"),
        ("Users", "Update"),
        ("Users", "Delete"),
        ("Jobs", "Create"),
        ("Jobs", "Read"),
        ("Jobs", "Update"),
        ("Jobs", "Delete"),
        ("Chatbots", "Create"),
        ("Chatbots", "Read"),
        ("Chatbots", "Update"),
        ("Chatbots", "Delete"),
        ("Google Forms", "Create"),
        ("Google Forms", "Read"),
        ("Google Forms", "Update"),
        ("Google Forms", "Delete"),
        ("Form Automation", "Create"),
        ("Form Automation", "Read"),
        ("Form Automation", "Update"),
        ("Form Automation", "Delete"),
        ("Podcasts", "Create"),
        ("Podcasts", "Read"),
        ("Podcasts", "Update"),
        ("Podcasts", "Delete"),
        ("Assignments", "Create"),
        ("Assignments", "Read"),
        ("Assignments", "Update"),
        ("Assignments", "Delete"),
        ("Dashboard", "Create"),
        ("Dashboard", "Read"),
        ("Dashboard", "Update"),
        ("Dashboard", "Delete"),
        ("Stickee", "Create"),
        ("Stickee", "Read"),
        ("Stickee", "Update"),
        ("Stickee", "Delete"),
        ("ToA", "Create"),
        ("ToA", "Read"),
        ("ToA", "Update"),
        ("ToA", "Delete"),
        ("Skill Assignments", "Create"),
        ("Skill Assignments", "Read"),
        ("Skill Assignments", "Update"),
        ("Skill Assignments", "Delete"),
        ("Questions", "Create"),
        ("Questions", "Read"),
        ("Questions", "Update"),
        ("Questions", "Delete"),
        ("Stickball Analytics", "Create"),
        ("Stickball Analytics", "Read"),
        ("Stickball Analytics", "Update"),
        ("Stickball Analytics", "Delete"),
        ("Products", "Create"),
        ("Products", "Read"),
        ("Products", "Update"),
        ("Products", "Delete"),
        ("Categories", "Create"),
        ("Categories", "Read"),
        ("Categories", "Update"),
        ("Categories", "Delete"),
        ("Import/Export", "Create"),
        ("Import/Export", "Read"),
        ("Import/Export", "Update"),
        ("Import/Export", "Delete"),
        ("Content Engine", "Create"),
        ("Content Engine", "Read"),
        ("Content Engine", "Update"),
        ("Content Engine", "Delete"),
        ("AI Videos", "Create"),
        ("AI Videos", "Read"),
        ("AI Videos", "Update"),
        ("AI Videos", "Delete"),
        ("Dictionary", "Create"),
        ("Dictionary", "Read"),
        ("Dictionary", "Update"),
        ("Dictionary", "Delete"),
        ("Aisles", "Create"),
        ("Aisles", "Read"),
        ("Aisles", "Update"),
        ("Aisles", "Delete"),
        ("Tips", "Create"),
        ("Tips", "Read"),
        ("Tips", "Update"),
        ("Tips", "Delete"),
        ("Grocery Products", "Create"),
        ("Grocery Products", "Read"),
        ("Grocery Products", "Update"),
        ("Grocery Products", "Delete"),
        ("Stocks", "Create"),
        ("Stocks", "Read"),
        ("Stocks", "Update"),
        ("Stocks", "Delete"),
        ("Planner", "Create"),
        ("Planner", "Read"),
        ("Planner", "Update"),
        ("Planner", "Delete"),
        ("Planner Analytics", "Create"),
        ("Planner Analytics", "Read"),
        ("Planner Analytics", "Update"),
        ("Planner Analytics", "Delete"),
        ("Teacher View", "Create"),
        ("Teacher View", "Read"),
        ("Teacher View", "Update"),
        ("Teacher View", "Delete"),
        ("Content Marketplace", "Create"),
        ("Content Marketplace", "Read"),
        ("Content Marketplace", "Update"),
        ("Content Marketplace", "Delete"),
        ("Grade Level", "Create"),
        ("Grade Level", "Read"),
        ("Grade Level", "Update"),
        ("Grade Level", "Delete"),
        ("Internal Chatbot", "Create"),
        ("Internal Chatbot", "Read"),
        ("Internal Chatbot", "Update"),
        ("Internal Chatbot", "Delete"),
        ("Notifications", "Create"),
        ("Notifications", "Read"),
        ("Notifications", "Update"),
        ("Notifications", "Delete"),
        ("Permissions", "Create"),
        ("Permissions", "Read"),
        ("Permissions", "Update"),
        ("Permissions", "Delete"),
        ("Permission Copy", "Create"),
        ("Permission Copy", "Read"),
        ("Permission Copy", "Update"),
        ("Permission Copy", "Delete")
    ]

    for pc in permission_copies:
        data = (pc[0], pc[1])  # Ensure it's a tuple
        postgres_cursor.execute(insert_query, data)

    print(f"{BColors.OKGREEN}Permission_copies migration completed{BColors.ENDC}")
